# Generated by Django 5.0.6 on 2024-05-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_budget_category_timeperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='timeperiod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.timeperiod'),
        ),
    ]
