# Generated by Django 5.0.6 on 2024-06-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_currenttimeperiod_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttimeperiod',
            name='type',
            field=models.CharField(choices=[('week', 'week'), ('month', 'month'), ('year', 'year')], default='week', max_length=10),
        ),
    ]
