# Generated by Django 5.0.6 on 2024-06-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_currenttimeperiod_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currenttimeperiod',
            name='type',
        ),
    ]
